# Generated by Django 6.0.3 on 2026-03-16 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=12)),
                ('qr_prefix', models.CharField(default='EVT', max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='events/logos/')),
                ('qr_logo', models.ImageField(blank=True, upload_to='events/qr_logos/')),
                ('flyer', models.ImageField(blank=True, upload_to='events/flyers/')),
                ('qr_fill_color', models.CharField(default='#102542', max_length=7)),
                ('qr_background_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('qr_logo_background_color', models.CharField(default='#ffffff', max_length=7)),
                ('qr_logo_scale', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('access_policy', models.TextField(blank=True)),
                ('email_subject', models.CharField(default='Tu acceso esta listo: {event_name}', max_length=180)),
                ('email_preheader', models.CharField(default='Popayan se viste de negro - Todos de negro - Closing 2025', max_length=220)),
                ('email_heading', models.CharField(default='Hola {attendee_name}', max_length=180)),
                ('email_intro', models.TextField(default='Tu asistencia ha sido confirmada. Abajo tienes la info oficial del evento:')),
                ('email_message_title', models.CharField(default='Mensaje del evento', max_length=140)),
                ('email_body', models.TextField(default='Tu registro para {event_name} fue confirmado.\n\nSucursal: {branch_name}\nFecha: {event_date}\nCategoria: {category_name}\nQR: {qr_code}\n\nAdjuntamos tu codigo QR para el ingreso.')),
                ('email_warning_title', models.CharField(default='Importante', max_length=140)),
                ('email_warning_text', models.TextField(default='Ingreso Early hasta las 11:00 PM. Despues de esa hora aplica multa de $25.000.')),
                ('email_details_title', models.CharField(default='Detalles', max_length=140)),
                ('email_date_text', models.CharField(default='{fecha_evento}', max_length=180)),
                ('email_time_text', models.CharField(default='{hora_evento}', max_length=120)),
                ('venue_name', models.CharField(default='Terrazas Campestres - K3 Via Totoro', max_length=220)),
                ('maps_url', models.URLField(blank=True)),
                ('maps_label', models.CharField(default='Abrir en Google Maps', max_length=120)),
                ('dress_code', models.CharField(default='Todos de negro', max_length=160)),
                ('email_qr_title', models.CharField(default='Tu codigo QR esta adjunto a este correo', max_length=180)),
                ('email_qr_note', models.CharField(default='Presentalo junto a tu cedula en la entrada.', max_length=220)),
                ('email_footer', models.CharField(default='Presenta este correo en la entrada del evento.', max_length=220)),
                ('email_closing_text', models.CharField(default='Nos vemos pronto.', max_length=220)),
                ('email_team_signature', models.CharField(default='Equipo {event_name}', max_length=220)),
                ('email_legal_note', models.CharField(default='Correo automatico - conserva tu QR hasta el dia del evento.', max_length=220)),
                ('email_background_color', models.CharField(default='#f6f2eb', max_length=7)),
                ('email_card_color', models.CharField(default='#ffffff', max_length=7)),
                ('email_header_background_color', models.CharField(default='#111315', max_length=7)),
                ('email_text_color', models.CharField(default='#172121', max_length=7)),
                ('email_muted_text_color', models.CharField(default='#bdbdbd', max_length=7)),
                ('email_accent_color', models.CharField(default='#c44536', max_length=7)),
                ('email_border_color', models.CharField(default='#1f1f22', max_length=7)),
                ('email_section_background_color', models.CharField(default='#18191b', max_length=7)),
                ('email_warning_background_color', models.CharField(default='#2a1c17', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-starts_at', 'name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'slug'), name='events_event_branch_slug_uniq')],
            },
        ),
    ]
