# Generated by Django 6.0.3 on 2026-03-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sucursal', 'Administrador de sucursal'), ('evento', 'Administrador de eventos'), ('entrada', 'Personal de entrada'), ('barra', 'Personal de barra')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='branches.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresia de sucursal',
                'verbose_name_plural': 'Membresias de sucursal',
                'ordering': ['branch__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='identity_membership_user_branch_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UserEventAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sucursal', 'Administrador de sucursal'), ('evento', 'Administrador de eventos'), ('entrada', 'Personal de entrada'), ('barra', 'Personal de barra')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='branches.branch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignacion de personal por evento',
                'verbose_name_plural': 'Asignaciones de personal por evento',
                'ordering': ['event__starts_at', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event'), name='identity_assignment_user_event_uniq')],
            },
        ),
    ]
