# Generated by Django 6.0.3 on 2026-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('code_prefix', models.CharField(default='DMT', max_length=12)),
                ('primary_color', models.CharField(default='#1d3557', max_length=7)),
                ('secondary_color', models.CharField(default='#e63946', max_length=7)),
                ('page_background_color', models.CharField(default='#f4f1ea', max_length=7)),
                ('surface_color', models.CharField(default='#fffdf8', max_length=7)),
                ('panel_color', models.CharField(default='#efe7dc', max_length=7)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('logo', models.ImageField(blank=True, upload_to='branches/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['name'],
            },
        ),
    ]
