# Generated by Django 6.0.3 on 2026-03-16 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('branch_logo', 'Logo de sucursal'), ('event_logo', 'Logo de evento'), ('event_qr_logo', 'Logo de QR del evento'), ('event_flyer', 'Flyer de evento'), ('product_image', 'Imagen de producto'), ('attendee_qr', 'QR de asistente')], max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('checksum', models.CharField(max_length=64)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Activo multimedia',
                'verbose_name_plural': 'Activos multimedia',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'kind'), name='media_assets_owner_kind_uniq')],
            },
        ),
    ]
