"""
Django settings for evento project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-w!+v6uela@#b+$)8^@95n1f1v&8b(*txblina)i2rqorgkf()w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# configuracion de ip cmd config
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "*",  # <-- Reemplaza esto, ej: '192.168.1.5'
    ".ngrok-free.app",
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",  # Custom app for core functionality
    "django_extensions",  # Useful for development
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "evento.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Directory for custom templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "evento.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "evento_db",
        "USER": "root",
        "PASSWORD": "12345678",  # Cambia por tu contraseña
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_USER_MODEL = 'core.Usuario'

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-es"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Configuración de autenticación
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Añade esta línea al final del archivo. El '*' actúa como comodín.
CSRF_TRUSTED_ORIGINS = ["https://*.ngrok-free.app"]


# --- INICIO DEL CÓDIGO AGREGADO ---
# Forzar HTTPS en producción y desarrollo con SSL
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
# --- FIN DEL CÓDIGO AGREGADO ---


# Agregar al final de settings.py

# ===== CONFIGURACIÓN DE EMAIL =====
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'zamamotas@gmail.com'  # CAMBIAR por tu email real
EMAIL_HOST_PASSWORD = 'uxxg iyhg rgsb xbmw'  # CAMBIAR por tu contraseña de aplicación
DEFAULT_FROM_EMAIL = 'DMT 69 Event <zamamotas@gmail.com>'


# PASOS PARA OBTENER LA CONTRASEÑA DE APLICACIÓN:
# 1. Ve a https://myaccount.google.com/
# 2. Seguridad → Verificación en 2 pasos (actívala si no está)
# 3. Contraseñas de aplicaciones → Selecciona "Correo" → Generar
# 4. Copia la contraseña de 16 caracteres (ej: abcd efgh ijkl mnop)
# 5. Úsala en EMAIL_HOST_PASSWORD (CON espacios o sin espacios)

# ===== CONFIGURACIÓN DEL EVENTO =====
EVENTO_NOMBRE = 'DMT 69'
EVENTO_FECHA = '31 de Diciembre 2025'
EVENTO_HORA = '10:00 PM'
EVENTO_LUGAR = 'Mocoa, Putumayo'