# Generated by Django 6.0.3 on 2026-03-16 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        ('branches', '0001_initial'),
        ('catalog', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_group', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_included_consumption', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='attendees.attendee')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='branches.branch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='events.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.product')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_v2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de barra',
                'verbose_name_plural': 'Ventas de barra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarSalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('transfer_proof', models.ImageField(blank=True, upload_to='sales/proofs/')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.barsale')),
            ],
            options={
                'verbose_name': 'Pago de venta de barra',
                'verbose_name_plural': 'Pagos de ventas de barra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('entrada', 'Entrada'), ('barra', 'Barra')], max_length=20)),
                ('movement_type', models.CharField(choices=[('evento_dia', 'Dia de evento'), ('gasto', 'Gasto'), ('vaciar_caja', 'Vaciar caja')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('attendee_quantity', models.PositiveIntegerField(default=0)),
                ('unit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='branches.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_movements', to='events.event')),
            ],
            options={
                'verbose_name': 'Movimiento de caja',
                'verbose_name_plural': 'Movimientos de caja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('transfer_proof', models.ImageField(blank=True, upload_to='cash/proofs/')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.cashmovement')),
            ],
            options={
                'verbose_name': 'Pago de movimiento',
                'verbose_name_plural': 'Pagos de movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EventProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('event_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_products', to='branches.branch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_settings', to='events.event')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_settings', to='catalog.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_product_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto habilitado por evento',
                'verbose_name_plural': 'Productos habilitados por evento',
                'ordering': ['product__name'],
                'unique_together': {('event', 'product')},
            },
        ),
    ]
