# Generated by Django 5.2.12 on 2026-03-17 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='created_role',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador global'), ('sucursal', 'Administrador de sucursal'), ('evento', 'Administrador de eventos'), ('entrada', 'Personal de entrada'), ('barra', 'Personal de barra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
